language: node_js
node_js:
  - lts/*
os:
  - linux
  - osx
addons:
  apt:
    packages: rlwrap
  homebrew:
    packages: clojure
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=/opt/clj/bin:"$PATH"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && ! which clojure; then curl https://download.clojure.org/install/linux-install-1.9.0.358.sh | sudo bash -s - -p /opt/clj; fi
  - which java clojure node npm make
install:
  - make install
script:
  - make
cache:
  directories:
    - /opt/clj
    - ~/.m2/
    - ~/.npm/
    - ~/.pkg-cache/
    - .cpcache
    - node_modules
notifications:
  email:
    on_success: never
